server:
  port: 0

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
app:
  mode: init
logging:
  level:
    root: INFO
    xyz.lingview.dimstack: DEBUG